### ISSUE TITLE
Deprecation Warning

### ISSUE THREAD

**Issue by bathienle** [waliens/sldc#11]
Running my application with SLDC generates several deprecation warnings:
`sldc/workflow.py:160: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  tile_polygons = np.array([polygons for result in tiles_polygons for _, polygons in result])`

`sldc/merger.py:212: ShapelyDeprecationWarning: The 'cascaded_union()' function is deprecated. Use 'unary_union()' instead.
  polygon = cascaded_union(polygons).buffer(-dilation_dist, join_style=join)`

`sldc/merger.py:155: ShapelyDeprecationWarning: __len__ for multi-part geometries is deprecated and will be removed in Shapely 2.0. Check the length of the geoms property instead to get the  number of parts of a multi-part geometry.
  return np.array(merged_polygons), np.array(merged_labels)`

**Comment by waliens** [comment]
fixed in c4dea30efde7854ead70b265ba97af17fb0f6e0e
